AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - com.amazonaws.serverless.archetypes::aws-serverless-springboot3-archetype
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  AwsServerlessSpringboot3ArchetypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.example.weather_app.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  AwsServerlessSpringboot3ArchetypeApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: AwsServerlessSpringboot3ArchetypeApi
