package com.example.weather_app.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.Data;

@JsonIgnoreProperties(ignoreUnknown = true)
@DynamoDBTable(tableName = "Weather")
@Data
public class WeatherRespDTO {
	
	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	private String id;
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	@DynamoDBAttribute
	private String name;
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getCountry() {
		return country;
	}
	public void setCountry(String country) {
		this.country = country;
	}
	public String getWeatherDescription() {
		return weatherDescription;
	}
	public void setWeatherDescription(String weatherDescription) {
		this.weatherDescription = weatherDescription;
	}
	public Double getTemperature() {
		return temperature;
	}
	public void setTemperature(Double temperature) {
		this.temperature = temperature;
	}
	public int getHumidity() {
		return humidity;
	}
	public void setHumidity(int humidity) {
		this.humidity = humidity;
	}
	public double getWindSpeed() {
		return windSpeed;
	}
	public void setWindSpeed(double windSpeed) {
		this.windSpeed = windSpeed;
	}
	@DynamoDBAttribute
	private String country;
	@DynamoDBAttribute
	private String weatherDescription;
	@DynamoDBAttribute
	private Double temperature;
	@DynamoDBAttribute
	private int humidity;
	@DynamoDBAttribute
	private double windSpeed;
	
	@Override
	public String toString() {
		return "{" + "id=" + id + ",city='" + name + '\'' +  ", country=" + 
	                    country 
	                    + ", weatherDescription=" + weatherDescription
	                    + ", temperature=" + temperature + 
	                    ", humidity=" + humidity + ", windSpeed=" + windSpeed + 
	                    '}';
	}


}
